### PR TITLE
webpack 4 migration

### PR DESCRIPTION
**Pull request by headfire94**
there is migration to webpack 4. main changes are - plugin hooks

### CODE REVIEW

**Comment by mike1808** [comment]
Thanks for the PR. I will have a look to this in a couple of days. I personally stopped using this with Webpack v4 and started using [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin)

**Comment by jeyj0** [comment]
Hi, can you tell me the status of the PR? I'd like to use this plugin and don't see how mini-css-extract-plugin is an alternative? It'd be awesome if there'd be webpack 4 support, or a hint as to how to replace the functionality by said plugin? Thanks in advance!

**Comment by ChristianGrete** [comment]
Hi, I really need this plugin to work with webpack 4. Could you please give an update on when and/or if this is going to be merged?

**Comment by mike1808** [comment]
@headfire94  sorry for late response. PR looks ok, however, I'd like to see backward compatibilities with Webpack v3 since it is still in use.

@headfire94 can you add checks for `compilation.hooks` and use hooks only when  their are avaiable and fallback to the old API when there are not? Like in [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin/blob/master/index.js#L55)

**Comment by jeyj0** [comment]
I don't think backwards compatibility is necessary, as it is easy to simply use the older version when necessary? Just a thought though. It's customary to simply use a major version for a case like this. But in the end it's your choice.

**Comment by mike1808** [comment]
@jeyj0 well, that sounds reasonable. I will merge this and bump the major version

**Comment by jeyj0** [comment]
Awesome, thanks a lot! :D

**Comment by mike1808** [comment]
Version v1.0.0 is published.

**Pull request merged**
